### ISSUE TITLE
Download raw video frames

### ISSUE THREAD

**Issue by thaolmk54** [noagarcia/knowit-rock#1]
Hi,

Thank you for the great work.
Just wondering where can I download the raw video frames as well as the pre-computed visual concepts of the dataset ? Looks like you provided some local server links that people don't have access to.

**Comment by noagarcia** [comment]
Hi, thank you for your interest on our work. We do not officially distribute the frames as per copyright issues. However, if you send me an email, we will provide you with the details on how to obtain them.

Best regards,
Noa

**Comment by BruceKenas** [comment]
Can you send me the raw video frames as well as the pre computed visual concept of the dataset?
My email: brucepham98@gmail.com

Many thanks.

**Comment by zarif98sjs** [comment]
Hi, can any of you send me the links for the video frames?
Email: zarif98sjs@gmail.com

Thanks in advance!

@BruceKenas @thaolmk54 @noagarcia
